# Copyright 2018 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add preceding_job_id to StartConditions

Revision ID: 01ed1d28f119
Revises: a8899f1b2311
Create Date: 2017-05-04 15:05:56.439412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ed1d28f119'
down_revision = 'a8899f1b2311'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('start_conditions', sa.Column('preceding_job_id', sa.Integer(), nullable=True))
  op.create_foreign_key(None, 'start_conditions', 'jobs', ['preceding_job_id'], ['id'])
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, 'start_conditions', type_='foreignkey')
  op.drop_column('start_conditions', 'preceding_job_id')
  # ### end Alembic commands ###
