# Copyright 2018 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add run_on_schedule to Pipelines

Revision ID: 6056d0d0eff9
Revises: 95a62f05f603
Create Date: 2017-06-13 11:35:37.068515

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6056d0d0eff9'
down_revision = '95a62f05f603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('run_on_schedule', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'run_on_schedule')
    # ### end Alembic commands ###
