"""New model to track enqueued tasks.

Revision ID: e34417c82307
Revises: 1c013e45b9bb
Create Date: 2018-08-30 16:35:57.847064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e34417c82307'
down_revision = '1c013e45b9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enqueued_tasks',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('task_namespace', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('task_name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enqueued_tasks')
    # ### end Alembic commands ###
