# Copyright 2023 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add ouput and output parameters to ML models.

Revision ID: 2bf97a4419d7
Revises: 067ab7b58de0
Create Date: 2023-05-25 19:29:27.848917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf97a4419d7'
down_revision = '067ab7b58de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('ml_model_output',
                  sa.Column('created_at', sa.DateTime(), nullable=False),
                  sa.Column('updated_at', sa.DateTime(), nullable=False),
                  sa.Column('ml_model_id', sa.Integer(), nullable=False),
                  sa.Column('destination',
                            sa.String(length=255), nullable=False),
                  sa.ForeignKeyConstraint(
                      ['ml_model_id'], ['ml_models.id']),
                  sa.PrimaryKeyConstraint('ml_model_id'))
  op.create_table('ml_model_output_parameters',
                  sa.Column('created_at', sa.DateTime(), nullable=False),
                  sa.Column('updated_at', sa.DateTime(), nullable=False),
                  sa.Column('ml_model_id', sa.Integer(), nullable=False),
                  sa.Column('customer_id', sa.String(length=255),
                            nullable=True),
                  sa.Column('conversion_action_id',
                            sa.String(length=255), nullable=True),
                  sa.ForeignKeyConstraint(
                      ['ml_model_id'], ['ml_model_output.ml_model_id']),
                  sa.PrimaryKeyConstraint('ml_model_id'))
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('ml_model_output_parameters')
  op.drop_table('ml_model_output')
  # ### end Alembic commands ###
