# Copyright 2023 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add additional input parameters for the model.

Revision ID: 68237c98a20f
Revises: a13664809900
Create Date: 2024-02-05 20:32:56.168487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68237c98a20f'
down_revision = 'a13664809900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_input_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_analytics_project', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_analytics_dataset', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_party_project', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_input_parameters', schema=None) as batch_op:
        batch_op.drop_column('first_party_project')
        batch_op.drop_column('google_analytics_dataset')
        batch_op.drop_column('google_analytics_project')

    # ### end Alembic commands ###
