# Copyright 2024 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add comparison and value columns to model variables table.

Revision ID: 8b95ad532329
Revises: 68237c98a20f
Create Date: 2024-02-08 17:08:59.826480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b95ad532329'
down_revision = '68237c98a20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comparison', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('value', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_variables', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.drop_column('comparison')

    # ### end Alembic commands ###
