# Copyright 2018 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Create Pipelines

Revision ID: 94039d1c8c45
Revises:
Create Date: 2017-04-23 14:52:39.978915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94039d1c8c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('pipelines',
  sa.Column('id', sa.Integer(), nullable=False),
  sa.Column('name', sa.String(length=255), nullable=True),
  sa.Column('status', sa.String(length=50), nullable=False),
  sa.Column('status_changed_at', sa.DateTime(), nullable=True),
  sa.Column('created_at', sa.DateTime(), nullable=False),
  sa.Column('updated_at', sa.DateTime(), nullable=False),
  sa.PrimaryKeyConstraint('id')
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('pipelines')
  # ### end Alembic commands ###
