# Copyright 2018 Google Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""empty message

Revision ID: a1f205feb508
Revises: 01ed1d28f119
Create Date: 2017-05-25 14:43:06.300847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1f205feb508'
down_revision = '01ed1d28f119'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('jobs', sa.Column('enqueued_workers_count', sa.Integer(),
                                  nullable=False, server_default='0'))
  op.add_column('jobs', sa.Column('succeeded_workers_count', sa.Integer(),
                                  nullable=False, server_default='0'))
  op.add_column('jobs', sa.Column('failed_workers_count', sa.Integer(),
                                  nullable=False, server_default='0'))
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('jobs', 'enqueued_workers_count')
  op.drop_column('jobs', 'succeeded_workers_count')
  op.drop_column('jobs', 'failed_workers_count')
  # ### end Alembic commands ###
